# Generated by Django 4.2 on 2025-01-13 00:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minigames", "0003_remove_post_title_review_gamerate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="gamerate",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
