# Generated by Django 5.1.4 on 2025-01-19 22:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minigames", "0004_alter_review_gamerate"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="games/"),
        ),
    ]
