# Generated by Django 5.1.4 on 2025-01-27 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("minigames", "0008_remove_pcomment_author_remove_pcomment_post_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="review",
            name="edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="reaction",
            name="content_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="contenttypes.contenttype",
            ),
        ),
    ]
