# Generated by Django 5.1.4 on 2025-01-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minigames", "0009_comment_edited_post_edited_review_edited_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
