# Generated by Django 5.1.4 on 2025-01-27 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minigames", "0010_profile_bio_profile_birth_date_profile_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(
                blank=True,
                default="media/default_profile.png",
                null=True,
                upload_to="profiles/",
            ),
        ),
    ]
