# Generated by Django 5.1.4 on 2025-01-28 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("minigames", "0011_alter_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="image",
            field=models.ImageField(
                blank=True,
                default="media/default_profile.png",
                null=True,
                upload_to="games/",
            ),
        ),
    ]
